import { Injectable } from '@nestjs/common';
const PDFDocument = require('pdfkit');

@Injectable()
export class ReportingService {
  async generateCompliancePdf(data: {
    frameworkName: string;
    reportDate: Date;
    score: number;
    controls: any[];
    risks: any[];
    aiSummary?: any;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc
        .fontSize(24)
        .fillColor('#1e40af')
        .text('Compliance Report', { align: 'center' });
      doc
        .fontSize(14)
        .fillColor('#374151')
        .text(data.frameworkName, { align: 'center' });
      doc
        .fontSize(10)
        .fillColor('#6b7280')
        .text(`Generated: ${data.reportDate.toLocaleDateString()}`, {
          align: 'center',
        });
      doc.moveDown(2);

      // Compliance Score
      doc.fontSize(18).fillColor('#111827').text('Overall Compliance Score');
      const scoreColor =
        data.score >= 80 ? '#16a34a' : data.score >= 60 ? '#d97706' : '#dc2626';
      doc
        .fontSize(48)
        .fillColor(scoreColor)
        .text(`${data.score}%`, { align: 'center' });
      doc.moveDown(1);

      // Executive Summary
      if (data.aiSummary?.executiveSummary) {
        doc.fontSize(16).fillColor('#111827').text('Executive Summary');
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e5e7eb');
        doc.moveDown(0.5);
        doc
          .fontSize(11)
          .fillColor('#374151')
          .text(data.aiSummary.executiveSummary, { align: 'justify' });
        doc.moveDown(1);
      }

      // Controls Summary
      doc.fontSize(16).fillColor('#111827').text('Controls Summary');
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e5e7eb');
      doc.moveDown(0.5);

      const implemented = data.controls.filter(
        (c) => c.status === 'implemented',
      ).length;
      const inProgress = data.controls.filter(
        (c) => c.status === 'in_progress',
      ).length;
      const notStarted = data.controls.filter(
        (c) => c.status === 'not_started',
      ).length;

      doc
        .fontSize(11)
        .fillColor('#374151')
        .text(`Total Controls: ${data.controls.length}`);
      doc.fillColor('#16a34a').text(`✓ Implemented: ${implemented}`);
      doc.fillColor('#d97706').text(`⟳ In Progress: ${inProgress}`);
      doc.fillColor('#6b7280').text(`○ Not Started: ${notStarted}`);
      doc.moveDown(1);

      // Risks Summary
      doc.fontSize(16).fillColor('#111827').text('Risk Summary');
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e5e7eb');
      doc.moveDown(0.5);

      const critical = data.risks.filter(
        (r) => r.severity === 'critical',
      ).length;
      const high = data.risks.filter((r) => r.severity === 'high').length;
      const medium = data.risks.filter((r) => r.severity === 'medium').length;
      const low = data.risks.filter((r) => r.severity === 'low').length;

      doc.fontSize(11);
      doc.fillColor('#dc2626').text(`● Critical: ${critical}`);
      doc.fillColor('#ea580c').text(`● High: ${high}`);
      doc.fillColor('#d97706').text(`● Medium: ${medium}`);
      doc.fillColor('#16a34a').text(`● Low: ${low}`);
      doc.moveDown(1);

      // Key Findings
      if (data.aiSummary?.keyFindings?.length) {
        doc.fontSize(16).fillColor('#111827').text('Key Findings');
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e5e7eb');
        doc.moveDown(0.5);
        data.aiSummary.keyFindings.forEach((finding: string, i: number) => {
          doc
            .fontSize(11)
            .fillColor('#374151')
            .text(`${i + 1}. ${finding}`);
          doc.moveDown(0.3);
        });
        doc.moveDown(1);
      }

      // Footer
      doc
        .fontSize(9)
        .fillColor('#9ca3af')
        .text(
          'This report was generated by the AI-Powered Compliance Management Platform',
          { align: 'center' },
        );

      doc.end();
    });
  }

  async getComplianceTrend(frameworkId: string, days = 90) {
    const trend = Array.from({ length: Math.floor(days / 7) }, (_, i) => ({
      week: i + 1,
      score: Math.min(100, 40 + i * 2 + Math.floor(Math.random() * 5)),
      date: new Date(Date.now() - (days - i * 7) * 24 * 60 * 60 * 1000),
    }));
    return { frameworkId, trend };
  }
}
